### ISSUE TITLE
[BUG] Time format incorrect on playbook

### ISSUE THREAD

**Issue by katierik** [RedHatInsights/insights-remediations-frontend#114]
The time format on playbook does not match what is in the standard. 

Tooltip should have the format: "07 Jan 2019, 23:33 UTC”

![Xnip2019-05-14_08-30-19](https://user-images.githubusercontent.com/23172038/57698062-a45c7880-7622-11e9-84ca-3b82817d1d43.jpg)

UX standard: https://docs.google.com/document/d/1hivSfe48717VhlLRtjyqReS5twbSLuPC6MISJt3MTG4/edit?usp=sharing (Hopefully moving to the insights-frontend storybook soon!)

**Comment by jharting** [comment]
Fixed
