### ISSUE TITLE
playbook action link to advisor action incomplete

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [RedHatInsights/insights-remediations-frontend#75]
the link to a advisor action takes roughly the form of `$BASE/insights/platform/advisor/actions/$TAG/$NAME` the link from the playbook instead took the rough form of  `$BASE/insights/platform/advisor/actions/$NAME`

in testing we used a example action for https://access.redhat.com/insights/platform/advisor/actions/security/CVE_2017_5715_cpu_virt|VIRT_CVE_2017_5715_CPU_3_ONLYKERNEL
and the url linked in the playbook overview was https://access.redhat.com/insights/platform/advisor/actions/CVE_2017_5715_cpu_virt%7CVIRT_CVE_2017_5715_CPU_3_ONLYKERNEL

off hand its not clear to me if the issue stems from remediation itself or from a issue transferring data into it

**Comment by jharting** [comment]
opened https://github.com/RedHatInsights/insights-advisor-frontend/issues/187
